services:
  frontend:
  container_name: audiophile_frontend 
    build:    
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - proxy-network

  backend:
  container_name: audiophile_backend 
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3030:${PORT}'
    networks:
      - proxy-network
    environment:
      - NODE_ENV=production
      - PORT=${PORT}

networks:
  proxy-network:
    external: true
